version: "3.9"
services:
  configserver:
    image: ostock/config-server:1.0-SNAPSHOT
    ports:
      - "9999:9999"
    networks:
      backend:
        aliases:
          - "configserver"
  licensing:
    image: ostock/license:1.0-SNAPSHOT
    ports:
      - "8080:8080"
    environment:
      - "SPRING_PROFILES_ACTIVE=dev"
    networks:
      backend:
        aliases:
          - "licenseservice"

networks:
  backend:
    driver: bridge