spring:
  application:
    name: licensing-service
  jpa:
    open-in-view: false

application:
  organization-client-type: discovery #rest / feign / discovery

resilience4j:
  circuitbreaker:
    instances:
      licenseService:
        register-health-indicator: true
        allow-health-indicator-to-fail: true
        ring-buffer-size-in-closed-state: 5 # deprecated!
        ring-buffer-size-in-half-open-state: 3 # deprecated!
        wait-duration-in-open-state: 10s
        failure-rate-threshold: 50
        record-exceptions:
          - org.springframework.web.client.HttpServerErrorException
          - java.io.IOException
          - java.util.concurrent.TimeoutException
          - org.springframework.web.client.ResourceAccessException
  bulkhead:
    instances:
      bulkheadLicenseService:
        max-wait-duration: 2ms
        max-concurrent-calls: 20
  thread-pool-bulkhead:
    instances:
      bulkheadLicenseService:
        max-thread-pool-size: 1
        core-thread-pool-size: 1
        queue-capacity: 1
  retry:
    instances:
      retryLicenseService:
        max-attempts: 5
        wait-duration: 10s
        retry-exceptions:
          - java.util.concurrent.TimeoutException
  ratelimiter:
    instances:
      licenseService:
        timeout-duration: 1s
        limit-refresh-period: 5000
        limit-for-period: 5
