spring:
  application:
    name: organization-service
  jpa:
    open-in-view: false

  cloud:
    stream:
      bindings:
        output:
          destination: orgChangeTopic
          content-type: application/json
      kafka:
        binder:
          brokers: localhost
          zkNodes: localhost

logging:
  level:
    io.averkhoglyad.ostock: DEBUG
    org.springframework.security: DEBUG

keycloak:
  realm: ostock-realm
  auth-server-url: http://localhost:9090/auth
  ssl-required: external
  resource: ostock
  credentials:
    secret: c3ILalPuUs1KXsOUu0V5zpUIjY6b3QrW
  use-resource-role-mappings: true
  bearer-only: true


