spring:
  application:
    name: organization-service
  jpa:
    open-in-view: false

  cloud:
    stream:
      bindings:
        orgChange:
          destination: orgChangeTopic
          content-type: application/json
      kafka:
        binder:
          brokers: localhost
          zkNodes: localhost

logging:
  level:
    io.averkhoglyad.ostock: DEBUG
    org.springframework.security: DEBUG

keycloak:
  realm: ostock-realm
  auth-server-url: http://localhost:9090
  ssl-required: external
  resource: ostock
  credentials:
    secret: bHX3kkwK7HFRvZbEOA3cdmS7DIlh2ir4
  use-resource-role-mappings: true
  bearer-only: true


