spring:
  application:
    name: config-server
  profiles:
    active:
      - git
      - native
  cloud:
    config:
      server:
        git:
          uri: https://github.com/averkhoglyad/o-stock-configs.git
          default-label: master
          search-paths: configs
          force-pull: true
          order: 1
        native:
          search-locations: classpath:/conf
          order: 2
        encrypt:
          enabled: true
    refresh:
      enabled: true

server:
  port: 9999

encrypt:
  key: "foM}kcGHmxB7[C9:"

management:
  endpoints:
    web:
      exposure:
        include: "*"